# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0003_auto_20161207_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
