# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0005_auto_20161211_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='creator',
            new_name='user',
        ),
    ]
