# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0008_auto_20161212_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
