# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0009_auto_20161212_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='user_id',
            new_name='poster',
        ),
    ]
